# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 22:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PackProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag(2), regex='[0-9a-f]{6}')])),
                ('color_name', models.CharField(max_length=30, null=True)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenderSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('packs', models.ManyToManyField(to='cahgen.CardsList')),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='render_spec',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cahgen.RenderSpec'),
        ),
        migrations.AddField(
            model_name='cardslist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cahgen.PackProfile'),
        ),
    ]
