# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 00:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('cards', models.TextField(default='Example card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag(2), regex='[0-9a-f]{6}')])),
                ('color_name', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packprofiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID')),
                ('generated_content', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('packs', models.ManyToManyField(to='cahgen.CardsList')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pdf',
            name='render_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cahgen.RenderSpec'),
        ),
        migrations.AddField(
            model_name='cardslist',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cahgen.PackProfile'),
        ),
    ]
