# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cahgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
