# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cahgen', '0002_auto_20170911_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packprofile',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='renderspec',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='packprofile',
            name='private',
        ),
        migrations.AddField(
            model_name='cardslist',
            name='cards',
            field=models.TextField(default='Example card'),
        ),
        migrations.AddField(
            model_name='packprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='render_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cahgen.RenderSpec'),
        ),
    ]
