# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahgen', '0003_auto_20170918_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderspec',
            name='style',
            field=models.PositiveSmallIntegerField(choices=[(0, 'White cards'), (1, 'Black cards')], default=0),
            preserve_default=False,
        ),
    ]
