# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cahgen', '0003_auto_20170913_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardslist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={},
        ),
        migrations.AlterModelOptions(
            name='renderspec',
            options={},
        ),
    ]
