# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahgen', '0004_renderspec_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renderspec',
            name='style',
        ),
        migrations.AddField(
            model_name='cardslist',
            name='is_black',
            field=models.BooleanField(default=False),
        ),
    ]
