# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahgen', '0005_auto_20170918_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderspec',
            name='append_color',
            field=models.BooleanField(default=True),
        ),
    ]
